**What is numpy**? (talk)

**Let's do some coding **  
I'll be providing the list of numpy functions that i am going to show

In [1]:
import numpy as np #import the package

## Arrays and operation on them

In [3]:

#create an empty array
emptyArr = np.array([])
print (emptyArr)

[]


In [4]:
#lets append some values
arr = np.append(emptyArr,1)
print (arr)
arr = np.append(arr,2)
arr = np.append(arr,3)
print (arr)

[1.]
[1. 2. 3.]


In [5]:
#now check the dimension of the array
print (arr)
print ("shape is")
print (arr.shape)

[1. 2. 3.]
shape is
(3,)


In [6]:
#let's do some maths operation on our array
#calcualte the sum
total = np.sum(arr)
print ("sum is "+ str(total))

#square root of individual elemets
sqr = np.sqrt(arr)
print ("sqrt is" , end =' ')
print (sqr)

sum is 6.0
sqrt is [1.         1.41421356 1.73205081]


## Operation between two 1d arrays

In [8]:
#create two arrays using another way
ar1 = [1,2,3,4,5]
ar2 = [6,7,8,9,10]
# now make the numpy array
arr1 = np.array(ar1)
arr2 = np.array(ar2)
print (arr1)
print (arr2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [9]:
#let's to vector operation 
#add the two vector
add = np.add(arr1,arr2)
print ("addition is" , end=" ")
print (add)

#substract the two vector
sub = np.subtract(arr1,arr2)
print ("substraction is" , end = " ")
print (sub)

#take the element wise multiplcation
prod = np.multiply(arr1, arr2)
print ("product is", end = " ")
print (prod)
#or
prod = arr1 * arr2
print ("product is 2nd time", end = " ") 
print (prod)

addition is [ 7  9 11 13 15]
substraction is [-5 -5 -5 -5 -5]
product is [ 6 14 24 36 50]
product is 2nd time [ 6 14 24 36 50]


##Generating arrays automatically

In [10]:
#generate array of zeros
zeros = np.zeros(4) # take the dimension of array you want to create
print (zeros)

ones = np.ones(7)
print (ones)

[0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]


#Let's go 2d

In [11]:
#creates 2d matrix of zeros
zeros = np.zeros((4,4))
print (zeros)
print (zeros.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)


In [12]:

#ignore this line
arr = np.random.randint(1,10,(4,4))
print (arr)
print ()
print ("array2")
print ()
arr2 = np.random.randint(1,10,(4,4))
print (arr2)

[[2 9 1 3]
 [6 1 6 7]
 [9 2 3 2]
 [8 1 8 1]]

array2

[[8 5 5 5]
 [9 9 7 9]
 [5 6 9 1]
 [8 5 6 6]]


In [15]:
#math op on 2d array
#let's get the sum of all elements in arr
print ("sum is" + str(np.sum(arr)))

# sum for all element in a row
print ("sum along row is", end = " ") 
print (np.sum(arr, axis=0))

print ("sum along columns", end = " ")
print (np.sum(arr,axis=1))

#add a constant value to all elements of the matrix
print (arr)
print ("after adding")
print (arr+2)

#how to calculate transpose of a matrix
print ("transpose is")
print (arr.T)

sum is69
sum along row is [25 13 18 13]
sum along columns [15 20 16 18]
[[2 9 1 3]
 [6 1 6 7]
 [9 2 3 2]
 [8 1 8 1]]
after adding
[[ 4 11  3  5]
 [ 8  3  8  9]
 [11  4  5  4]
 [10  3 10  3]]
transpose is
[[2 6 9 8]
 [9 1 2 1]
 [1 6 3 8]
 [3 7 2 1]]


In [16]:
#let's see sum maths operation on 2d array
#let's add the array
total = arr + arr2
print ("addition is")
print (total)


addition is
[[10 14  6  8]
 [15 10 13 16]
 [14  8 12  3]
 [16  6 14  7]]


In [17]:

#dot product of two matrix
print (arr)
print ()
print (arr2)


[[2 9 1 3]
 [6 1 6 7]
 [9 2 3 2]
 [8 1 8 1]]

[[8 5 5 5]
 [9 9 7 9]
 [5 6 9 1]
 [8 5 6 6]]


In [18]:
#dimension of arr and arr2(4X4)
print (np.dot(arr,arr2))

[[126 112 100 110]
 [143 110 133  87]
 [121  91  98  78]
 [121 102 125  63]]


In [19]:
#slicing op internet

#one last complex function 
#hstack and vstack
# add a column vector in existing array
#make a column vector
col = np.ones((4,1))
print (col)
print ()
print (arr)

#let's add this column vector as our first column in the arr

newarr = np.hstack((col,arr))
print ()
print (newarr)

[[1.]
 [1.]
 [1.]
 [1.]]

[[2 9 1 3]
 [6 1 6 7]
 [9 2 3 2]
 [8 1 8 1]]

[[1. 2. 9. 1. 3.]
 [1. 6. 1. 6. 7.]
 [1. 9. 2. 3. 2.]
 [1. 8. 1. 8. 1.]]


In [20]:
#similarly vstack
row = np.ones((1,4))
print (np.vstack((row,arr)))

[[1. 1. 1. 1.]
 [2. 9. 1. 3.]
 [6. 1. 6. 7.]
 [9. 2. 3. 2.]
 [8. 1. 8. 1.]]


## List of numpy functions

In [21]:
#create an empty array
emptyArr = np.array([])

#lets append some values
arr = np.append(emptyArr,1)
arr = np.append(arr,2)
arr = np.append(arr,3)
#now check the dimension of the array
arr.shape

#let's do some maths operation on our array
#calcualte the sum
total = np.sum(arr)

#square root of individual elemets
sqr = np.sqrt(arr)

#create two arrays using another way
ar1 = [1,2,3,4,5]
ar2 = [6,7,8,9,10]
# now make the numpy array
arr1 = np.array(ar1)
arr2 = np.array(ar2)

#let's to vector operation 
#add the two vector
add = np.add(arr1,arr2)

#substract the two vector
sub = np.subtract(arr1,arr2)

#take the element wise multiplcation
prod = np.multiply(arr1, arr2)

#or
prod = arr1 * arr2

#generate array of zeros
zeros = np.zeros(4) # take the dimension of array you want to create
ones = np.ones(7)


#creates 2d matrix of zeros
zeros = np.zeros((4,4))
#ignore this line
arr = np.random.randint(1,10,(4,4))
arr2 = np.random.randint(1,10,(4,4))


#math op on 2d array
#let's get the sum of all elements in arr
np.sum(arr)


#sum for all element in a row
np.sum(arr, axis=0)
#print "sum along columns"
np.sum(arr,axis=1)


#add a constant value to all elements of the matrix
#arr
#arr+2

#how to calculate transpose of a matrix
arr.T


#let's see sum maths operation on 2d array
#let's add the array
total = arr + arr2

#dimension of arr and arr2(4X4)
np.dot(arr,arr2)

#one last complex function 
#hstack and vstack
# add a column vector in existing array
#make a column vector
col = np.ones((4,1))
#let's add this column vector as our first column in the arr
newarr = np.hstack((col,arr))

#similarly vstack
row = np.ones((1,4))
newarr = np.vstack((row,arr))




## Enough preknowledge let's go to coding